/* =======================================================
   MODELO: Sistema de Facturación para Restaurantes RestUNA
   Oracle 21c XE
   Fecha: 2025-01-14
   Descripción: Base de datos para sistema POS de restaurante
                con manejo de usuarios, secciones, menús, órdenes,
                facturación y cierres de caja
   ======================================================= */

-----------------------------------------------------------
-- 1) SECUENCIAS
-----------------------------------------------------------
CREATE SEQUENCE SEQ_USUARIO           START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SECCION           START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MESA              START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_GRUPO_PRODUCTO    START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTO          START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CLIENTE           START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ORDEN             START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_ORDEN     START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_FACTURA           START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_FACTURA   START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CIERRE_CAJA       START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PARAMETRO         START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ARCHIVO           START WITH 1 INCREMENT BY 1 NOMAXVALUE NOMINVALUE NOCYCLE NOCACHE;

-----------------------------------------------------------
-- 2) TABLAS
-----------------------------------------------------------

-- USUARIO (Administradores, Cajeros, Saloneros)
CREATE TABLE USUARIO(
  ID_USUARIO           NUMBER         NOT NULL,
  USUARIO              VARCHAR2(50)   NOT NULL,
  NOMBRE               VARCHAR2(100)  NOT NULL,
  CONTRASENA           VARCHAR2(255)  NOT NULL,
  ROL                  VARCHAR2(20)   NOT NULL,
  ESTADO               CHAR(1)        NOT NULL,
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  FECHA_ULTIMO_ACCESO  DATE,
  TOKEN_SESION         VARCHAR2(500),
  CONSTRAINT PK_USUARIO           PRIMARY KEY (ID_USUARIO),
  CONSTRAINT UQ_USUARIO_USUARIO   UNIQUE (USUARIO),
  CONSTRAINT CHK_USUARIO_ROL      CHECK (ROL IN ('ADMINISTRADOR','CAJERO','SALONERO')),
  CONSTRAINT CHK_USUARIO_ESTADO   CHECK (ESTADO IN ('A','I'))
);

-- SECCION (Salones, Barra, etc.)
CREATE TABLE SECCION(
  ID_SECCION           NUMBER         NOT NULL,
  NOMBRE               VARCHAR2(80)   NOT NULL,
  TIPO                 VARCHAR2(15)   NOT NULL,
  COBRA_IMPUESTO       CHAR(1)        NOT NULL,
  ESTADO               CHAR(1)        NOT NULL,
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  ID_ARCHIVO_IMAGEN    NUMBER,
  CONSTRAINT PK_SECCION           PRIMARY KEY (ID_SECCION),
  CONSTRAINT UQ_SECCION_NOMBRE    UNIQUE (NOMBRE),
  CONSTRAINT CHK_SECCION_TIPO     CHECK (TIPO IN ('SALON','BARRA','TERRAZA')),
  CONSTRAINT CHK_SECCION_IMPUESTO CHECK (COBRA_IMPUESTO IN ('S','N')),
  CONSTRAINT CHK_SECCION_ESTADO   CHECK (ESTADO IN ('A','I'))
);

-- MESA (Mesas de los salones)
CREATE TABLE MESA(
  ID_MESA              NUMBER         NOT NULL,
  ID_SECCION           NUMBER         NOT NULL,
  NUMERO_MESA          VARCHAR2(10)   NOT NULL,
  CAPACIDAD            NUMBER(2)      NOT NULL,
  POSICION_X           NUMBER(5,2),
  POSICION_Y           NUMBER(5,2),
  ESTADO               VARCHAR2(10)   NOT NULL,
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_MESA              PRIMARY KEY (ID_MESA),
  CONSTRAINT UQ_MESA_SECCION      UNIQUE (ID_SECCION, NUMERO_MESA),
  CONSTRAINT CHK_MESA_CAPACIDAD   CHECK (CAPACIDAD BETWEEN 1 AND 20),
  CONSTRAINT CHK_MESA_ESTADO      CHECK (ESTADO IN ('LIBRE','OCUPADA','RESERVADA','FUERA_SERVICIO'))
);

-- GRUPO_PRODUCTO (Categorías del menú)
CREATE TABLE GRUPO_PRODUCTO(
  ID_GRUPO_PRODUCTO    NUMBER         NOT NULL,
  NOMBRE               VARCHAR2(80)   NOT NULL,
  DESCRIPCION          VARCHAR2(200),
  ACCESO_RAPIDO        CHAR(1)        NOT NULL,
  ORDEN_VISUALIZACION  NUMBER(3)      NOT NULL,
  CANTIDAD_VENDIDA     NUMBER(10)     DEFAULT 0 NOT NULL,
  ESTADO               CHAR(1)        NOT NULL,
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_GRUPO_PRODUCTO        PRIMARY KEY (ID_GRUPO_PRODUCTO),
  CONSTRAINT UQ_GRUPO_NOMBRE          UNIQUE (NOMBRE),
  CONSTRAINT CHK_GRUPO_ACCESO         CHECK (ACCESO_RAPIDO IN ('S','N')),
  CONSTRAINT CHK_GRUPO_ESTADO         CHECK (ESTADO IN ('A','I'))
);

-- PRODUCTO (Productos del menú)
CREATE TABLE PRODUCTO(
  ID_PRODUCTO          NUMBER         NOT NULL,
  ID_GRUPO_PRODUCTO    NUMBER         NOT NULL,
  NOMBRE               VARCHAR2(120)  NOT NULL,
  NOMBRE_CORTO         VARCHAR2(30)   NOT NULL,
  DESCRIPCION          VARCHAR2(300),
  PRECIO               NUMBER(10,2)   NOT NULL,
  ACCESO_RAPIDO        CHAR(1)        NOT NULL,
  CANTIDAD_VENDIDA     NUMBER(10)     DEFAULT 0 NOT NULL,
  ESTADO               CHAR(1)        NOT NULL,
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_PRODUCTO              PRIMARY KEY (ID_PRODUCTO),
  CONSTRAINT UQ_PRODUCTO_NOMBRE       UNIQUE (NOMBRE),
  CONSTRAINT UQ_PRODUCTO_CORTO        UNIQUE (NOMBRE_CORTO),
  CONSTRAINT CHK_PRODUCTO_PRECIO      CHECK (PRECIO > 0),
  CONSTRAINT CHK_PRODUCTO_ACCESO      CHECK (ACCESO_RAPIDO IN ('S','N')),
  CONSTRAINT CHK_PRODUCTO_ESTADO      CHECK (ESTADO IN ('A','I'))
);

-- CLIENTE (Información de clientes)
CREATE TABLE CLIENTE(
  ID_CLIENTE           NUMBER         NOT NULL,
  NOMBRE               VARCHAR2(100),
  APELLIDOS            VARCHAR2(120),
  CEDULA               VARCHAR2(20),
  TELEFONO             VARCHAR2(20),
  CORREO               VARCHAR2(120),
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CLIENTE           PRIMARY KEY (ID_CLIENTE),
  CONSTRAINT UQ_CLIENTE_CEDULA    UNIQUE (CEDULA),
  CONSTRAINT UQ_CLIENTE_CORREO    UNIQUE (CORREO)
);

-- ORDEN (Órdenes de los clientes)
CREATE TABLE ORDEN(
  ID_ORDEN             NUMBER         NOT NULL,
  ID_MESA              NUMBER,
  ID_SECCION           NUMBER         NOT NULL,
  ID_CLIENTE           NUMBER,
  ID_USUARIO_SALONERO  NUMBER         NOT NULL,
  NUMERO_ORDEN         VARCHAR2(20)   NOT NULL,
  FECHA_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  ESTADO               VARCHAR2(15)   NOT NULL,
  OBSERVACIONES        VARCHAR2(500),
  SUBTOTAL             NUMBER(10,2)   DEFAULT 0 NOT NULL,
  CONSTRAINT PK_ORDEN             PRIMARY KEY (ID_ORDEN),
  CONSTRAINT UQ_ORDEN_NUMERO      UNIQUE (NUMERO_ORDEN),
  CONSTRAINT CHK_ORDEN_ESTADO     CHECK (ESTADO IN ('ABIERTA','FACTURADA','CANCELADA')),
  CONSTRAINT CHK_ORDEN_SUBTOTAL   CHECK (SUBTOTAL >= 0)
);

-- DETALLE_ORDEN (Productos de cada orden)
CREATE TABLE DETALLE_ORDEN(
  ID_DETALLE_ORDEN     NUMBER         NOT NULL,
  ID_ORDEN             NUMBER         NOT NULL,
  ID_PRODUCTO          NUMBER         NOT NULL,
  CANTIDAD             NUMBER(5,2)    NOT NULL,
  PRECIO_UNITARIO      NUMBER(10,2)   NOT NULL,
  SUBTOTAL             NUMBER(10,2)   NOT NULL,
  OBSERVACIONES        VARCHAR2(200),
  CONSTRAINT PK_DETALLE_ORDEN         PRIMARY KEY (ID_DETALLE_ORDEN),
  CONSTRAINT CHK_DETALLE_CANTIDAD     CHECK (CANTIDAD > 0),
  CONSTRAINT CHK_DETALLE_PRECIO       CHECK (PRECIO_UNITARIO > 0),
  CONSTRAINT CHK_DETALLE_SUBTOTAL     CHECK (SUBTOTAL >= 0)
);

-- FACTURA (Facturas emitidas)
CREATE TABLE FACTURA(
  ID_FACTURA           NUMBER         NOT NULL,
  ID_ORDEN             NUMBER,
  ID_CLIENTE           NUMBER,
  ID_USUARIO_CAJERO    NUMBER         NOT NULL,
  NUMERO_FACTURA       VARCHAR2(20)   NOT NULL,
  FECHA_FACTURA        DATE           DEFAULT SYSDATE NOT NULL,
  SUBTOTAL             NUMBER(12,2)   NOT NULL,
  IMPUESTO_VENTA       NUMBER(10,2)   DEFAULT 0 NOT NULL,
  IMPUESTO_SERVICIO    NUMBER(10,2)   DEFAULT 0 NOT NULL,
  DESCUENTO            NUMBER(10,2)   DEFAULT 0 NOT NULL,
  TOTAL                NUMBER(12,2)   NOT NULL,
  EFECTIVO_RECIBIDO    NUMBER(12,2)   DEFAULT 0 NOT NULL,
  TARJETA_RECIBIDO     NUMBER(12,2)   DEFAULT 0 NOT NULL,
  VUELTO               NUMBER(10,2)   DEFAULT 0 NOT NULL,
  ESTADO               VARCHAR2(15)   NOT NULL,
  CORREO_ENVIADO       CHAR(1)        DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_FACTURA               PRIMARY KEY (ID_FACTURA),
  CONSTRAINT UQ_FACTURA_NUMERO        UNIQUE (NUMERO_FACTURA),
  CONSTRAINT CHK_FACTURA_SUBTOTAL     CHECK (SUBTOTAL >= 0),
  CONSTRAINT CHK_FACTURA_TOTAL        CHECK (TOTAL >= 0),
  CONSTRAINT CHK_FACTURA_ESTADO       CHECK (ESTADO IN ('ACTIVA','ANULADA')),
  CONSTRAINT CHK_FACTURA_CORREO       CHECK (CORREO_ENVIADO IN ('S','N'))
);

-- DETALLE_FACTURA (Productos facturados)
CREATE TABLE DETALLE_FACTURA(
  ID_DETALLE_FACTURA   NUMBER         NOT NULL,
  ID_FACTURA           NUMBER         NOT NULL,
  ID_PRODUCTO          NUMBER         NOT NULL,
  CANTIDAD             NUMBER(5,2)    NOT NULL,
  PRECIO_UNITARIO      NUMBER(10,2)   NOT NULL,
  SUBTOTAL             NUMBER(10,2)   NOT NULL,
  CONSTRAINT PK_DETALLE_FACTURA       PRIMARY KEY (ID_DETALLE_FACTURA),
  CONSTRAINT CHK_DETFACT_CANTIDAD     CHECK (CANTIDAD > 0),
  CONSTRAINT CHK_DETFACT_PRECIO       CHECK (PRECIO_UNITARIO > 0),
  CONSTRAINT CHK_DETFACT_SUBTOTAL     CHECK (SUBTOTAL >= 0)
);

-- CIERRE_CAJA (Control de cierres por cajero)
CREATE TABLE CIERRE_CAJA(
  ID_CIERRE_CAJA       NUMBER         NOT NULL,
  ID_USUARIO_CAJERO    NUMBER         NOT NULL,
  FECHA_APERTURA       DATE           NOT NULL,
  FECHA_CIERRE         DATE,
  EFECTIVO_INICIAL     NUMBER(12,2)   DEFAULT 0 NOT NULL,
  EFECTIVO_SISTEMA     NUMBER(12,2)   DEFAULT 0 NOT NULL,
  EFECTIVO_DECLARADO   NUMBER(12,2)   DEFAULT 0 NOT NULL,
  TARJETA_SISTEMA      NUMBER(12,2)   DEFAULT 0 NOT NULL,
  TARJETA_DECLARADO    NUMBER(12,2)   DEFAULT 0 NOT NULL,
  DIFERENCIA_EFECTIVO  NUMBER(10,2)   DEFAULT 0 NOT NULL,
  DIFERENCIA_TARJETA   NUMBER(10,2)   DEFAULT 0 NOT NULL,
  TOTAL_FACTURAS       NUMBER(6)      DEFAULT 0 NOT NULL,
  ESTADO               VARCHAR2(10)   NOT NULL,
  OBSERVACIONES        VARCHAR2(500),
  CONSTRAINT PK_CIERRE_CAJA           PRIMARY KEY (ID_CIERRE_CAJA),
  CONSTRAINT CHK_CIERRE_ESTADO        CHECK (ESTADO IN ('ABIERTO','CERRADO'))
);

-- PARAMETRO (Configuración del sistema)
CREATE TABLE PARAMETRO(
  ID_PARAMETRO         NUMBER         NOT NULL,
  ID_USUARIO           NUMBER         NOT NULL,
  CLAVE                VARCHAR2(50)   NOT NULL,
  VALOR                VARCHAR2(200)  NOT NULL,
  DESCRIPCION          VARCHAR2(300)  NOT NULL,
  TIPO_DATO            VARCHAR2(20)   NOT NULL,
  FECHA_MODIFICACION   DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_PARAMETRO         PRIMARY KEY (ID_PARAMETRO),
  CONSTRAINT UQ_PARAMETRO_USUARIO_CLAVE UNIQUE (ID_USUARIO, CLAVE),
  CONSTRAINT CHK_PARAMETRO_TIPO   CHECK (TIPO_DATO IN ('STRING','NUMBER','BOOLEAN','DATE'))
);

-- ARCHIVO (Almacenamiento de archivos en BD)
CREATE TABLE ARCHIVO(
  ID_ARCHIVO           NUMBER         NOT NULL,
  NOMBRE_ARCHIVO       VARCHAR2(200)  NOT NULL,
  TIPO_MIME            VARCHAR2(100)  NOT NULL,
  TAMANIO              NUMBER(12)     NOT NULL,
  CONTENIDO            BLOB           NOT NULL,
  FECHA_SUBIDA         DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_ARCHIVO           PRIMARY KEY (ID_ARCHIVO),
  CONSTRAINT CHK_ARCHIVO_TAMANIO  CHECK (TAMANIO > 0)
);

-----------------------------------------------------------
-- 3) ÍNDICES PARA RENDIMIENTO
-----------------------------------------------------------
CREATE INDEX IDX_USUARIO_ROL            ON USUARIO (ROL);
CREATE INDEX IDX_MESA_SECCION           ON MESA (ID_SECCION);
CREATE INDEX IDX_MESA_ESTADO            ON MESA (ESTADO);
CREATE INDEX IDX_PRODUCTO_GRUPO         ON PRODUCTO (ID_GRUPO_PRODUCTO);
CREATE INDEX IDX_PRODUCTO_ACCESO        ON PRODUCTO (ACCESO_RAPIDO);
CREATE INDEX IDX_ORDEN_MESA             ON ORDEN (ID_MESA);
CREATE INDEX IDX_ORDEN_SECCION          ON ORDEN (ID_SECCION);
CREATE INDEX IDX_ORDEN_USUARIO          ON ORDEN (ID_USUARIO_SALONERO);
CREATE INDEX IDX_ORDEN_ESTADO           ON ORDEN (ESTADO);
CREATE INDEX IDX_ORDEN_FECHA            ON ORDEN (FECHA_CREACION DESC);
CREATE INDEX IDX_DETALLE_ORDEN_ORDEN    ON DETALLE_ORDEN (ID_ORDEN);
CREATE INDEX IDX_DETALLE_ORDEN_PROD     ON DETALLE_ORDEN (ID_PRODUCTO);
CREATE INDEX IDX_FACTURA_USUARIO        ON FACTURA (ID_USUARIO_CAJERO);
CREATE INDEX IDX_FACTURA_FECHA          ON FACTURA (FECHA_FACTURA DESC);
CREATE INDEX IDX_DETALLE_FACT_FACT      ON DETALLE_FACTURA (ID_FACTURA);
CREATE INDEX IDX_DETALLE_FACT_PROD      ON DETALLE_FACTURA (ID_PRODUCTO);
CREATE INDEX IDX_CIERRE_USUARIO         ON CIERRE_CAJA (ID_USUARIO_CAJERO);
CREATE INDEX IDX_CIERRE_FECHA           ON CIERRE_CAJA (FECHA_APERTURA DESC);

-----------------------------------------------------------
-- 4) FOREIGN KEYS
-----------------------------------------------------------
ALTER TABLE SECCION
  ADD CONSTRAINT FK_SECCION_ARCHIVO
    FOREIGN KEY (ID_ARCHIVO_IMAGEN)
    REFERENCES ARCHIVO (ID_ARCHIVO);

ALTER TABLE MESA
  ADD CONSTRAINT FK_MESA_SECCION
    FOREIGN KEY (ID_SECCION)
    REFERENCES SECCION (ID_SECCION)
    ON DELETE CASCADE;

ALTER TABLE PRODUCTO
  ADD CONSTRAINT FK_PRODUCTO_GRUPO
    FOREIGN KEY (ID_GRUPO_PRODUCTO)
    REFERENCES GRUPO_PRODUCTO (ID_GRUPO_PRODUCTO);

ALTER TABLE ORDEN
  ADD CONSTRAINT FK_ORDEN_MESA
    FOREIGN KEY (ID_MESA)
    REFERENCES MESA (ID_MESA);

ALTER TABLE ORDEN
  ADD CONSTRAINT FK_ORDEN_SECCION
    FOREIGN KEY (ID_SECCION)
    REFERENCES SECCION (ID_SECCION);

ALTER TABLE ORDEN
  ADD CONSTRAINT FK_ORDEN_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE ORDEN
  ADD CONSTRAINT FK_ORDEN_USUARIO
    FOREIGN KEY (ID_USUARIO_SALONERO)
    REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE DETALLE_ORDEN
  ADD CONSTRAINT FK_DETALLE_ORDEN_ORDEN
    FOREIGN KEY (ID_ORDEN)
    REFERENCES ORDEN (ID_ORDEN)
    ON DELETE CASCADE;

ALTER TABLE DETALLE_ORDEN
  ADD CONSTRAINT FK_DETALLE_ORDEN_PRODUCTO
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE FACTURA
  ADD CONSTRAINT FK_FACTURA_ORDEN
    FOREIGN KEY (ID_ORDEN)
    REFERENCES ORDEN (ID_ORDEN);

ALTER TABLE FACTURA
  ADD CONSTRAINT FK_FACTURA_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE FACTURA
  ADD CONSTRAINT FK_FACTURA_USUARIO
    FOREIGN KEY (ID_USUARIO_CAJERO)
    REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE DETALLE_FACTURA
  ADD CONSTRAINT FK_DETALLE_FACTURA_FACTURA
    FOREIGN KEY (ID_FACTURA)
    REFERENCES FACTURA (ID_FACTURA)
    ON DELETE CASCADE;

ALTER TABLE DETALLE_FACTURA
  ADD CONSTRAINT FK_DETALLE_FACTURA_PRODUCTO
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE CIERRE_CAJA
  ADD CONSTRAINT FK_CIERRE_USUARIO
    FOREIGN KEY (ID_USUARIO_CAJERO)
    REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE PARAMETRO
  ADD CONSTRAINT FK_PARAMETRO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID_USUARIO)
    ON DELETE CASCADE;

-----------------------------------------------------------
-- 5) TRIGGERS (auto-ID y protección de actualización de PK)
-----------------------------------------------------------

-- USUARIO
CREATE OR REPLACE TRIGGER ts_Usuario_SEQ_USUARIO
BEFORE INSERT ON USUARIO FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL OR :NEW.ID_USUARIO <= 0 THEN
    :NEW.ID_USUARIO := SEQ_USUARIO.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Usuario_SEQ_USUARIO
AFTER UPDATE OF ID_USUARIO ON USUARIO FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001,'No se puede modificar ID_USUARIO (secuencia).');
END;
/

-- SECCION
CREATE OR REPLACE TRIGGER ts_Seccion_SEQ_SECCION
BEFORE INSERT ON SECCION FOR EACH ROW
BEGIN
  IF :NEW.ID_SECCION IS NULL OR :NEW.ID_SECCION <= 0 THEN
    :NEW.ID_SECCION := SEQ_SECCION.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Seccion_SEQ_SECCION
AFTER UPDATE OF ID_SECCION ON SECCION FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20002,'No se puede modificar ID_SECCION (secuencia).');
END;
/

-- MESA
CREATE OR REPLACE TRIGGER ts_Mesa_SEQ_MESA
BEFORE INSERT ON MESA FOR EACH ROW
BEGIN
  IF :NEW.ID_MESA IS NULL OR :NEW.ID_MESA <= 0 THEN
    :NEW.ID_MESA := SEQ_MESA.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Mesa_SEQ_MESA
AFTER UPDATE OF ID_MESA ON MESA FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20003,'No se puede modificar ID_MESA (secuencia).');
END;
/

-- GRUPO_PRODUCTO
CREATE OR REPLACE TRIGGER ts_GrupoProducto_SEQ_GRUPO_PRODUCTO
BEFORE INSERT ON GRUPO_PRODUCTO FOR EACH ROW
BEGIN
  IF :NEW.ID_GRUPO_PRODUCTO IS NULL OR :NEW.ID_GRUPO_PRODUCTO <= 0 THEN
    :NEW.ID_GRUPO_PRODUCTO := SEQ_GRUPO_PRODUCTO.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_GrupoProducto_SEQ_GRUPO_PRODUCTO
AFTER UPDATE OF ID_GRUPO_PRODUCTO ON GRUPO_PRODUCTO FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20004,'No se puede modificar ID_GRUPO_PRODUCTO (secuencia).');
END;
/

-- PRODUCTO
CREATE OR REPLACE TRIGGER ts_Producto_SEQ_PRODUCTO
BEFORE INSERT ON PRODUCTO FOR EACH ROW
BEGIN
  IF :NEW.ID_PRODUCTO IS NULL OR :NEW.ID_PRODUCTO <= 0 THEN
    :NEW.ID_PRODUCTO := SEQ_PRODUCTO.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Producto_SEQ_PRODUCTO
AFTER UPDATE OF ID_PRODUCTO ON PRODUCTO FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20005,'No se puede modificar ID_PRODUCTO (secuencia).');
END;
/

-- CLIENTE
CREATE OR REPLACE TRIGGER ts_Cliente_SEQ_CLIENTE
BEFORE INSERT ON CLIENTE FOR EACH ROW
BEGIN
  IF :NEW.ID_CLIENTE IS NULL OR :NEW.ID_CLIENTE <= 0 THEN
    :NEW.ID_CLIENTE := SEQ_CLIENTE.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Cliente_SEQ_CLIENTE
AFTER UPDATE OF ID_CLIENTE ON CLIENTE FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20006,'No se puede modificar ID_CLIENTE (secuencia).');
END;
/

-- ORDEN
CREATE OR REPLACE TRIGGER ts_Orden_SEQ_ORDEN
BEFORE INSERT ON ORDEN FOR EACH ROW
BEGIN
  IF :NEW.ID_ORDEN IS NULL OR :NEW.ID_ORDEN <= 0 THEN
    :NEW.ID_ORDEN := SEQ_ORDEN.NEXTVAL;
  END IF;
  -- Generar número de orden automático
  IF :NEW.NUMERO_ORDEN IS NULL THEN
    :NEW.NUMERO_ORDEN := 'ORD-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(:NEW.ID_ORDEN, 6, '0');
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Orden_SEQ_ORDEN
AFTER UPDATE OF ID_ORDEN ON ORDEN FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20007,'No se puede modificar ID_ORDEN (secuencia).');
END;
/

-- DETALLE_ORDEN
CREATE OR REPLACE TRIGGER ts_DetalleOrden_SEQ_DETALLE_ORDEN
BEFORE INSERT ON DETALLE_ORDEN FOR EACH ROW
BEGIN
  IF :NEW.ID_DETALLE_ORDEN IS NULL OR :NEW.ID_DETALLE_ORDEN <= 0 THEN
    :NEW.ID_DETALLE_ORDEN := SEQ_DETALLE_ORDEN.NEXTVAL;
  END IF;
  -- Calcular subtotal automáticamente
  :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;
/
CREATE OR REPLACE TRIGGER tsu_DetalleOrden_SEQ_DETALLE_ORDEN
AFTER UPDATE OF ID_DETALLE_ORDEN ON DETALLE_ORDEN FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20008,'No se puede modificar ID_DETALLE_ORDEN (secuencia).');
END;
/

-- FACTURA
CREATE OR REPLACE TRIGGER ts_Factura_SEQ_FACTURA
BEFORE INSERT ON FACTURA FOR EACH ROW
BEGIN
  IF :NEW.ID_FACTURA IS NULL OR :NEW.ID_FACTURA <= 0 THEN
    :NEW.ID_FACTURA := SEQ_FACTURA.NEXTVAL;
  END IF;
  -- Generar número de factura automático
  IF :NEW.NUMERO_FACTURA IS NULL THEN
    :NEW.NUMERO_FACTURA := 'FACT-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(:NEW.ID_FACTURA, 6, '0');
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Factura_SEQ_FACTURA
AFTER UPDATE OF ID_FACTURA ON FACTURA FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20009,'No se puede modificar ID_FACTURA (secuencia).');
END;
/

-- DETALLE_FACTURA
CREATE OR REPLACE TRIGGER ts_DetalleFactura_SEQ_DETALLE_FACTURA
BEFORE INSERT ON DETALLE_FACTURA FOR EACH ROW
BEGIN
  IF :NEW.ID_DETALLE_FACTURA IS NULL OR :NEW.ID_DETALLE_FACTURA <= 0 THEN
    :NEW.ID_DETALLE_FACTURA := SEQ_DETALLE_FACTURA.NEXTVAL;
  END IF;
  -- Calcular subtotal automáticamente
  :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;
/
CREATE OR REPLACE TRIGGER tsu_DetalleFactura_SEQ_DETALLE_FACTURA
AFTER UPDATE OF ID_DETALLE_FACTURA ON DETALLE_FACTURA FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'No se puede modificar ID_DETALLE_FACTURA (secuencia).');
END;
/

-- CIERRE_CAJA
CREATE OR REPLACE TRIGGER ts_CierreCaja_SEQ_CIERRE_CAJA
BEFORE INSERT ON CIERRE_CAJA FOR EACH ROW
BEGIN
  IF :NEW.ID_CIERRE_CAJA IS NULL OR :NEW.ID_CIERRE_CAJA <= 0 THEN
    :NEW.ID_CIERRE_CAJA := SEQ_CIERRE_CAJA.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_CierreCaja_SEQ_CIERRE_CAJA
AFTER UPDATE OF ID_CIERRE_CAJA ON CIERRE_CAJA FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20011,'No se puede modificar ID_CIERRE_CAJA (secuencia).');
END;
/

-- PARAMETRO
CREATE OR REPLACE TRIGGER ts_Parametro_SEQ_PARAMETRO
BEFORE INSERT ON PARAMETRO FOR EACH ROW
BEGIN
  IF :NEW.ID_PARAMETRO IS NULL OR :NEW.ID_PARAMETRO <= 0 THEN
    :NEW.ID_PARAMETRO := SEQ_PARAMETRO.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Parametro_SEQ_PARAMETRO
AFTER UPDATE OF ID_PARAMETRO ON PARAMETRO FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20012,'No se puede modificar ID_PARAMETRO (secuencia).');
END;
/

-- ARCHIVO
CREATE OR REPLACE TRIGGER ts_Archivo_SEQ_ARCHIVO
BEFORE INSERT ON ARCHIVO FOR EACH ROW
BEGIN
  IF :NEW.ID_ARCHIVO IS NULL OR :NEW.ID_ARCHIVO <= 0 THEN
    :NEW.ID_ARCHIVO := SEQ_ARCHIVO.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER tsu_Archivo_SEQ_ARCHIVO
AFTER UPDATE OF ID_ARCHIVO ON ARCHIVO FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20013,'No se puede modificar ID_ARCHIVO (secuencia).');
END;
/

-----------------------------------------------------------
-- 6) TRIGGERS DE NEGOCIO
-----------------------------------------------------------

-- Actualizar estado de mesa cuando se crea/modifica orden
CREATE OR REPLACE TRIGGER tr_Orden_Estado_Mesa
AFTER INSERT OR UPDATE OR DELETE ON ORDEN FOR EACH ROW
BEGIN
  -- Actualizar estado de mesa al insertar orden
  IF INSERTING AND :NEW.ID_MESA IS NOT NULL THEN
    UPDATE MESA SET ESTADO = 'OCUPADA' 
    WHERE ID_MESA = :NEW.ID_MESA AND ESTADO = 'LIBRE';
  END IF;
  
  -- Actualizar estado de mesa al cambiar estado de orden
  IF UPDATING AND :NEW.ESTADO = 'FACTURADA' AND :NEW.ID_MESA IS NOT NULL THEN
    UPDATE MESA SET ESTADO = 'LIBRE' 
    WHERE ID_MESA = :NEW.ID_MESA;
  END IF;
  
  -- Liberar mesa al eliminar orden
  IF DELETING AND :OLD.ID_MESA IS NOT NULL THEN
    UPDATE MESA SET ESTADO = 'LIBRE' 
    WHERE ID_MESA = :OLD.ID_MESA;
  END IF;
END;
/

-- Actualizar subtotal de orden al modificar detalles
CREATE OR REPLACE TRIGGER tr_DetalleOrden_Actualizar_Subtotal
AFTER INSERT OR UPDATE OR DELETE ON DETALLE_ORDEN FOR EACH ROW
DECLARE
  v_subtotal NUMBER(10,2);
BEGIN
  -- Calcular nuevo subtotal de la orden
  IF INSERTING OR UPDATING THEN
    SELECT NVL(SUM(SUBTOTAL), 0) INTO v_subtotal 
    FROM DETALLE_ORDEN WHERE ID_ORDEN = :NEW.ID_ORDEN;
    
    UPDATE ORDEN SET SUBTOTAL = v_subtotal 
    WHERE ID_ORDEN = :NEW.ID_ORDEN;
  END IF;
  
  IF DELETING THEN
    SELECT NVL(SUM(SUBTOTAL), 0) INTO v_subtotal 
    FROM DETALLE_ORDEN WHERE ID_ORDEN = :OLD.ID_ORDEN;
    
    UPDATE ORDEN SET SUBTOTAL = v_subtotal 
    WHERE ID_ORDEN = :OLD.ID_ORDEN;
  END IF;
END;
/

-- Actualizar contador de ventas de productos
CREATE OR REPLACE TRIGGER tr_DetalleFactura_Contador_Ventas
AFTER INSERT ON DETALLE_FACTURA FOR EACH ROW
BEGIN
  -- Actualizar contador del producto
  UPDATE PRODUCTO 
  SET CANTIDAD_VENDIDA = CANTIDAD_VENDIDA + :NEW.CANTIDAD
  WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;
  
  -- Actualizar contador del grupo
  UPDATE GRUPO_PRODUCTO 
  SET CANTIDAD_VENDIDA = CANTIDAD_VENDIDA + :NEW.CANTIDAD
  WHERE ID_GRUPO_PRODUCTO = (
    SELECT ID_GRUPO_PRODUCTO FROM PRODUCTO WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO
  );
END;
/

-----------------------------------------------------------
-- 7) COMENTARIOS (tablas y columnas)
-----------------------------------------------------------

-- USUARIO
COMMENT ON TABLE  USUARIO IS 'Usuarios del sistema: administradores, cajeros y saloneros con autenticación y roles.';
COMMENT ON COLUMN USUARIO.ID_USUARIO           IS 'Identificador único del usuario (asignado por secuencia).';
COMMENT ON COLUMN USUARIO.USUARIO              IS 'Nombre de usuario para login (único en el sistema).';
COMMENT ON COLUMN USUARIO.NOMBRE               IS 'Nombre completo o visible del usuario.';
COMMENT ON COLUMN USUARIO.CONTRASENA           IS 'Contraseña en texto plano (temporal, se cifrará con JWTokenHelper más adelante).';
COMMENT ON COLUMN USUARIO.ROL                  IS 'Rol del usuario: ADMINISTRADOR, CAJERO o SALONERO.';
COMMENT ON COLUMN USUARIO.ESTADO               IS 'Estado del usuario: A=Activo, I=Inactivo.';
COMMENT ON COLUMN USUARIO.FECHA_CREACION       IS 'Fecha de creación del registro.';
COMMENT ON COLUMN USUARIO.FECHA_ULTIMO_ACCESO  IS 'Fecha y hora del último acceso exitoso al sistema.';
COMMENT ON COLUMN USUARIO.TOKEN_SESION         IS 'Token JWT para sesión activa (opcional).';

-- SECCION
COMMENT ON TABLE  SECCION IS 'Secciones del restaurante: salones con mesas, barras, terrazas, etc.';
COMMENT ON COLUMN SECCION.ID_SECCION           IS 'Identificador único de la sección (asignado por secuencia).';
COMMENT ON COLUMN SECCION.NOMBRE               IS 'Nombre de la sección (único): Salón Principal, Barra, Terraza, etc.';
COMMENT ON COLUMN SECCION.TIPO                 IS 'Tipo de sección: SALON (con mesas), BARRA (venta directa), TERRAZA.';
COMMENT ON COLUMN SECCION.COBRA_IMPUESTO       IS 'Indica si en esta sección se cobra impuesto de servicio: S=Sí, N=No.';
COMMENT ON COLUMN SECCION.ESTADO               IS 'Estado de la sección: A=Activa, I=Inactiva.';
COMMENT ON COLUMN SECCION.FECHA_CREACION       IS 'Fecha de creación del registro.';
COMMENT ON COLUMN SECCION.ID_ARCHIVO_IMAGEN    IS 'Referencia al archivo de imagen de la mesa para diseño visual (FK).';

-- MESA
COMMENT ON TABLE  MESA IS 'Mesas de los salones con posición gráfica y estados para el sistema táctil.';
COMMENT ON COLUMN MESA.ID_MESA              IS 'Identificador único de la mesa (asignado por secuencia).';
COMMENT ON COLUMN MESA.ID_SECCION           IS 'Sección a la que pertenece la mesa (FK).';
COMMENT ON COLUMN MESA.NUMERO_MESA          IS 'Número o nombre de la mesa (único por sección).';
COMMENT ON COLUMN MESA.CAPACIDAD            IS 'Capacidad de personas de la mesa (1-20).';
COMMENT ON COLUMN MESA.POSICION_X           IS 'Posición X en el diseño gráfico del salón.';
COMMENT ON COLUMN MESA.POSICION_Y           IS 'Posición Y en el diseño gráfico del salón.';
COMMENT ON COLUMN MESA.ESTADO               IS 'Estado actual: LIBRE, OCUPADA, RESERVADA, FUERA_SERVICIO.';
COMMENT ON COLUMN MESA.FECHA_CREACION       IS 'Fecha de creación del registro.';

-- GRUPO_PRODUCTO
COMMENT ON TABLE  GRUPO_PRODUCTO IS 'Categorías de productos del menú: bebidas, platos fuertes, postres, etc.';
COMMENT ON COLUMN GRUPO_PRODUCTO.ID_GRUPO_PRODUCTO    IS 'Identificador único del grupo (asignado por secuencia).';
COMMENT ON COLUMN GRUPO_PRODUCTO.NOMBRE               IS 'Nombre del grupo: Bebidas Calientes, Platos Fuertes, etc.';
COMMENT ON COLUMN GRUPO_PRODUCTO.DESCRIPCION          IS 'Descripción del grupo de productos.';
COMMENT ON COLUMN GRUPO_PRODUCTO.ACCESO_RAPIDO        IS 'Incluir en menú de acceso rápido: S=Sí, N=No.';
COMMENT ON COLUMN GRUPO_PRODUCTO.ORDEN_VISUALIZACION  IS 'Orden de visualización en pantalla táctil.';
COMMENT ON COLUMN GRUPO_PRODUCTO.CANTIDAD_VENDIDA     IS 'Contador de productos vendidos del grupo (para ordenamiento).';
COMMENT ON COLUMN GRUPO_PRODUCTO.ESTADO               IS 'Estado del grupo: A=Activo, I=Inactivo.';
COMMENT ON COLUMN GRUPO_PRODUCTO.FECHA_CREACION       IS 'Fecha de creación del registro.';

-- PRODUCTO
COMMENT ON TABLE  PRODUCTO IS 'Productos del menú del restaurante con precios y configuración de acceso rápido.';
COMMENT ON COLUMN PRODUCTO.ID_PRODUCTO          IS 'Identificador único del producto (asignado por secuencia).';
COMMENT ON COLUMN PRODUCTO.ID_GRUPO_PRODUCTO    IS 'Grupo al que pertenece el producto (FK).';
COMMENT ON COLUMN PRODUCTO.NOMBRE               IS 'Nombre completo del producto (único).';
COMMENT ON COLUMN PRODUCTO.NOMBRE_CORTO         IS 'Nombre corto para pantalla de selección (único).';
COMMENT ON COLUMN PRODUCTO.DESCRIPCION          IS 'Descripción detallada del producto.';
COMMENT ON COLUMN PRODUCTO.PRECIO               IS 'Precio unitario del producto (mayor a 0).';
COMMENT ON COLUMN PRODUCTO.ACCESO_RAPIDO        IS 'Incluir en menú de acceso rápido: S=Sí, N=No.';
COMMENT ON COLUMN PRODUCTO.CANTIDAD_VENDIDA     IS 'Contador de unidades vendidas (para ordenamiento por popularidad).';
COMMENT ON COLUMN PRODUCTO.ESTADO               IS 'Estado del producto: A=Activo, I=Inactivo.';
COMMENT ON COLUMN PRODUCTO.FECHA_CREACION       IS 'Fecha de creación del registro.';

-- CLIENTE
COMMENT ON TABLE  CLIENTE IS 'Información de clientes para facturación y envío de correos.';
COMMENT ON COLUMN CLIENTE.ID_CLIENTE           IS 'Identificador único del cliente (asignado por secuencia).';
COMMENT ON COLUMN CLIENTE.NOMBRE               IS 'Nombre del cliente (opcional).';
COMMENT ON COLUMN CLIENTE.APELLIDOS            IS 'Apellidos del cliente (opcional).';
COMMENT ON COLUMN CLIENTE.CEDULA               IS 'Número de cédula del cliente (único, opcional).';
COMMENT ON COLUMN CLIENTE.TELEFONO             IS 'Teléfono del cliente.';
COMMENT ON COLUMN CLIENTE.CORREO               IS 'Correo electrónico para envío de facturas (único, opcional).';
COMMENT ON COLUMN CLIENTE.FECHA_CREACION       IS 'Fecha de registro del cliente.';

-- ORDEN
COMMENT ON TABLE  ORDEN IS 'Órdenes de clientes tomadas por saloneros en mesas o secciones del restaurante.';
COMMENT ON COLUMN ORDEN.ID_ORDEN             IS 'Identificador único de la orden (asignado por secuencia).';
COMMENT ON COLUMN ORDEN.ID_MESA              IS 'Mesa donde se toma la orden (opcional, FK).';
COMMENT ON COLUMN ORDEN.ID_SECCION           IS 'Sección del restaurante donde se toma la orden (FK).';
COMMENT ON COLUMN ORDEN.ID_CLIENTE           IS 'Cliente asociado a la orden (opcional, FK).';
COMMENT ON COLUMN ORDEN.ID_USUARIO_SALONERO  IS 'Salonero que toma la orden (FK).';
COMMENT ON COLUMN ORDEN.NUMERO_ORDEN         IS 'Número único de orden generado automáticamente.';
COMMENT ON COLUMN ORDEN.FECHA_CREACION       IS 'Fecha y hora de creación de la orden.';
COMMENT ON COLUMN ORDEN.ESTADO               IS 'Estado: ABIERTA, FACTURADA, CANCELADA.';
COMMENT ON COLUMN ORDEN.OBSERVACIONES        IS 'Observaciones especiales de la orden.';
COMMENT ON COLUMN ORDEN.SUBTOTAL             IS 'Subtotal calculado automáticamente de los detalles.';

-- DETALLE_ORDEN
COMMENT ON TABLE  DETALLE_ORDEN IS 'Productos incluidos en cada orden con cantidades y precios.';
COMMENT ON COLUMN DETALLE_ORDEN.ID_DETALLE_ORDEN     IS 'Identificador único del detalle (asignado por secuencia).';
COMMENT ON COLUMN DETALLE_ORDEN.ID_ORDEN             IS 'Orden a la que pertenece el detalle (FK).';
COMMENT ON COLUMN DETALLE_ORDEN.ID_PRODUCTO          IS 'Producto solicitado (FK).';
COMMENT ON COLUMN DETALLE_ORDEN.CANTIDAD             IS 'Cantidad solicitada del producto.';
COMMENT ON COLUMN DETALLE_ORDEN.PRECIO_UNITARIO      IS 'Precio unitario al momento de la orden.';
COMMENT ON COLUMN DETALLE_ORDEN.SUBTOTAL             IS 'Subtotal calculado: cantidad × precio_unitario.';
COMMENT ON COLUMN DETALLE_ORDEN.OBSERVACIONES        IS 'Observaciones específicas del producto (sin cebolla, etc.).';

-- FACTURA
COMMENT ON TABLE  FACTURA IS 'Facturas emitidas por cajeros con cálculos de impuestos, descuentos y formas de pago.';
COMMENT ON COLUMN FACTURA.ID_FACTURA           IS 'Identificador único de la factura (asignado por secuencia).';
COMMENT ON COLUMN FACTURA.ID_ORDEN             IS 'Orden que se factura (opcional, FK).';
COMMENT ON COLUMN FACTURA.ID_CLIENTE           IS 'Cliente al que se emite la factura (opcional, FK).';
COMMENT ON COLUMN FACTURA.ID_USUARIO_CAJERO    IS 'Cajero que emite la factura (FK).';
COMMENT ON COLUMN FACTURA.NUMERO_FACTURA       IS 'Número único de factura generado automáticamente.';
COMMENT ON COLUMN FACTURA.FECHA_FACTURA        IS 'Fecha y hora de emisión de la factura.';
COMMENT ON COLUMN FACTURA.SUBTOTAL             IS 'Subtotal antes de impuestos y descuentos.';
COMMENT ON COLUMN FACTURA.IMPUESTO_VENTA       IS 'Monto del impuesto de venta aplicado.';
COMMENT ON COLUMN FACTURA.IMPUESTO_SERVICIO    IS 'Monto del impuesto de servicio aplicado.';
COMMENT ON COLUMN FACTURA.DESCUENTO            IS 'Monto del descuento aplicado.';
COMMENT ON COLUMN FACTURA.TOTAL                IS 'Total final a pagar.';
COMMENT ON COLUMN FACTURA.EFECTIVO_RECIBIDO    IS 'Monto recibido en efectivo.';
COMMENT ON COLUMN FACTURA.TARJETA_RECIBIDO     IS 'Monto recibido con tarjeta.';
COMMENT ON COLUMN FACTURA.VUELTO               IS 'Vuelto entregado al cliente.';
COMMENT ON COLUMN FACTURA.ESTADO               IS 'Estado de la factura: ACTIVA, ANULADA.';
COMMENT ON COLUMN FACTURA.CORREO_ENVIADO       IS 'Indica si se envió por correo: S=Sí, N=No.';

-- DETALLE_FACTURA
COMMENT ON TABLE  DETALLE_FACTURA IS 'Productos facturados con cantidades y precios finales.';
COMMENT ON COLUMN DETALLE_FACTURA.ID_DETALLE_FACTURA   IS 'Identificador único del detalle (asignado por secuencia).';
COMMENT ON COLUMN DETALLE_FACTURA.ID_FACTURA           IS 'Factura a la que pertenece el detalle (FK).';
COMMENT ON COLUMN DETALLE_FACTURA.ID_PRODUCTO          IS 'Producto facturado (FK).';
COMMENT ON COLUMN DETALLE_FACTURA.CANTIDAD             IS 'Cantidad facturada del producto.';
COMMENT ON COLUMN DETALLE_FACTURA.PRECIO_UNITARIO      IS 'Precio unitario al momento de facturar.';
COMMENT ON COLUMN DETALLE_FACTURA.SUBTOTAL             IS 'Subtotal calculado: cantidad × precio_unitario.';

-- CIERRE_CAJA
COMMENT ON TABLE  CIERRE_CAJA IS 'Control de apertura y cierre de caja por cajero con cuadre de efectivo y tarjetas.';
COMMENT ON COLUMN CIERRE_CAJA.ID_CIERRE_CAJA       IS 'Identificador único del cierre (asignado por secuencia).';
COMMENT ON COLUMN CIERRE_CAJA.ID_USUARIO_CAJERO    IS 'Cajero responsable del cierre (FK).';
COMMENT ON COLUMN CIERRE_CAJA.FECHA_APERTURA       IS 'Fecha y hora de apertura de caja.';
COMMENT ON COLUMN CIERRE_CAJA.FECHA_CIERRE         IS 'Fecha y hora de cierre de caja.';
COMMENT ON COLUMN CIERRE_CAJA.EFECTIVO_INICIAL     IS 'Efectivo inicial declarado en apertura.';
COMMENT ON COLUMN CIERRE_CAJA.EFECTIVO_SISTEMA     IS 'Efectivo calculado por el sistema según facturas.';
COMMENT ON COLUMN CIERRE_CAJA.EFECTIVO_DECLARADO   IS 'Efectivo declarado por el cajero al cierre.';
COMMENT ON COLUMN CIERRE_CAJA.TARJETA_SISTEMA      IS 'Monto en tarjetas calculado por el sistema.';
COMMENT ON COLUMN CIERRE_CAJA.TARJETA_DECLARADO    IS 'Monto en tarjetas declarado por el cajero.';
COMMENT ON COLUMN CIERRE_CAJA.DIFERENCIA_EFECTIVO  IS 'Diferencia en efectivo (declarado - sistema).';
COMMENT ON COLUMN CIERRE_CAJA.DIFERENCIA_TARJETA   IS 'Diferencia en tarjetas (declarado - sistema).';
COMMENT ON COLUMN CIERRE_CAJA.TOTAL_FACTURAS       IS 'Cantidad total de facturas emitidas en el turno.';
COMMENT ON COLUMN CIERRE_CAJA.ESTADO               IS 'Estado del cierre: ABIERTO, CERRADO.';
COMMENT ON COLUMN CIERRE_CAJA.OBSERVACIONES        IS 'Observaciones del cierre de caja.';

-- PARAMETRO
COMMENT ON TABLE  PARAMETRO IS 'Parámetros de configuración del sistema por cada administrador: impuestos, descuentos, datos del restaurante.';
COMMENT ON COLUMN PARAMETRO.ID_PARAMETRO         IS 'Identificador único del parámetro (asignado por secuencia).';
COMMENT ON COLUMN PARAMETRO.ID_USUARIO           IS 'Usuario administrador dueño de esta configuración (FK).';
COMMENT ON COLUMN PARAMETRO.CLAVE                IS 'Clave del parámetro (IDIOMA, IMPUESTO_VENTA, etc.). Único por usuario.';
COMMENT ON COLUMN PARAMETRO.VALOR                IS 'Valor del parámetro.';
COMMENT ON COLUMN PARAMETRO.DESCRIPCION          IS 'Descripción del parámetro.';
COMMENT ON COLUMN PARAMETRO.TIPO_DATO            IS 'Tipo de dato: STRING, NUMBER, BOOLEAN, DATE.';
COMMENT ON COLUMN PARAMETRO.FECHA_MODIFICACION   IS 'Fecha de última modificación.';

-- ARCHIVO
COMMENT ON TABLE  ARCHIVO IS 'Almacenamiento de archivos en base de datos: imágenes de mesas, reportes PDF, etc.';
COMMENT ON COLUMN ARCHIVO.ID_ARCHIVO           IS 'Identificador único del archivo (asignado por secuencia).';
COMMENT ON COLUMN ARCHIVO.NOMBRE_ARCHIVO       IS 'Nombre original del archivo.';
COMMENT ON COLUMN ARCHIVO.TIPO_MIME            IS 'Tipo MIME del archivo (image/png, application/pdf, etc.).';
COMMENT ON COLUMN ARCHIVO.TAMANIO              IS 'Tamaño del archivo en bytes.';
COMMENT ON COLUMN ARCHIVO.CONTENIDO            IS 'Contenido binario del archivo (BLOB).';
COMMENT ON COLUMN ARCHIVO.FECHA_SUBIDA         IS 'Fecha de subida del archivo.';
