CREATE TABLE TURNO(
    ID NUMBER NOT NULL,
    USUARIO_ID NUMBER NOT NULL, 
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FINAL TIMESTAMP,
    DURACION NUMBER, 
    ESTADO VARCHAR2(1) NOT NULL,
    VERSION NUMBER DEFAULT 1,
    CONSTRAINT PK_TURNO PRIMARY KEY (ID),
    CONSTRAINT FK_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CHK_ESTADO CHECK (ESTADO IN ('A', 'F'))
  );

CREATE SEQUENCE SEQ_TURNO
  START WITH 1
  INCREMENT BY 1 
  NOCACHE
  NOCYCLE;

CREATE INDEX IDX_USUARIO ON TURNO(USUARIO_ID);

CREATE INDEX IDX_ESTADO ON TURNO(ESTADO);

COMMENT ON TABLE TURNO IS 'Control de turnos por empleado/usuario';
COMMENT ON COLUMN TURNO.ESTADO IS 'A = Activo, F = Finalizado';
COMMENT ON COLUMN TURNO.DURACION IS 'Duración en minutos';

